### ISSUE TITLE
Missing package from NPM

### ISSUE THREAD

**Issue by beyondtheobservableuniverse** [BePo65/mat-image-grid#63]
Hi

When i try to install in NPM with `npm install @bepo65/mat-image-grid` i got the following error: 
![image](https://github.com/user-attachments/assets/79319ac7-2e52-4a67-89a3-a73cdb56bf34)

**Comment by BePo65** [comment]
The package is still under construction (but already usable in its limits), so I did not publish it to npmjs already.

The limits are the number of images; at the moment it keeps all loaded image data from the server in the internal buffer;so the memory footprint might get very large for large image lists. I tested it with 10,000 images without running into problems.

At the moment i am working on the package to remove the limitation. This will change the interface (i.e. the properties defining the size of the buffers).

I will publish it anyway, but today i am very busy, Hope I will find the time tomorrow morning.

The package is not scoped, so it will be published as ´mat-image-grid´ (without the '@bepo65').
